/*
What is constructor ?
They are special member function that are automatically called upon the object creation.
They have the same name as of the class ot structure.

A default constructor is automatically generated by the compiler if the programmer does not define one.
This constructor doesn't take any argument as it is parameter less and initializes object members using default values.
It is also called a zero-argument constructor.
However, the default constructor is not generated by the compiler if the programmer has explicitly defined a constructor. 

*/

#include <iostream>
using namespace std;

class A{
	public:
		A(){
			cout<<"Constructor Called";
		}
};

int main(){
	A a;
	
	return 0;
}
